### ISSUE TITLE
Rounding of results.ops affects results

### ISSUE THREAD

**Issue by Beanow** [caderek/benny#13]
The `results.ops` value gets rounded from the underlying benchmark result:
https://github.com/caderek/benny/blob/970bf4f810b4d0bc4a22fbce3b71c712739b5a3a/src/internal/getCaseResult.ts#L12

This affects all further results being shared, such as the x% slower values. For slow operations (like single-digit ops), this will make result data very coarse. Regardless of tweaking to get a representative number of samples.

Example case:
```js
const b = require("benny");

const sleep = (n) => new Promise((res) => setTimeout(res, n));

b.suite(
  "Single digit ops",

  b.add("Should average 550ms", async () => {
    // Minimum delay.
    await sleep(500);
    // 100ms variance.
    await sleep(Math.random() * 100);
  }),

  b.add("Should average 420ms", async () => {
    // Minimum delay.
    await sleep(400);
    // 40ms variance.
    await sleep(Math.random() * 40);
  }),

  b.cycle()
);
```

Currently with rounding:
```
$ node slowOps.js 
Running "Single digit ops" suite...
Progress: 100%

  Should average 550ms:
    2 ops/s, ±3.24%   | fastest

  Should average 420ms:
    2 ops/s, ±1.32%   | 0% slower
```

Disabling rounding with ugly fix
```diff
- ops: Math.round(target.hz),
+ ops: target.hz,
```

```
$ node slowOps.js 
Running "Single digit ops" suite...
Progress: 100%

  Should average 550ms:
    1.8 144 016 838 170 172 ops/s, ±2.98%   | slowest, 23.18% slower

  Should average 420ms:
    2.3 618 417 935 942 433 ops/s, ±1.30%   | fastest
```

**Comment by caderek** [comment]
Thank you very much,
fixed with: https://github.com/caderek/benny/commit/7e112f55abcdcc24f7efed693182ff94eb5c84b1

Noe Benny will round results to the decimal place that guarantees the correct order, without being overly pedantic, the result for your example now looks something like this:

```
Running "Single digit ops" suite...
Progress: 100%

  Should average 550ms:
    1.8 ops/s, ±3.11%   | slowest, 21.74% slower

  Should average 420ms:
    2.3 ops/s, ±1.56%   | fastest
```
