### ISSUE TITLE
default cycle output incorrectly strips leading digits

### ISSUE THREAD

**Issue by mgartner** [caderek/benny#19]
With the suite:

```js
const B = require('benny');

B.suite(
  'test',

  B.add('t', () => {
    let i = 111111 % 123;
  }),

  B.cycle(),
  B.cycle((result) => {
    console.log(result);
  }),
);
```

The output is:

```
Running "test" suite...
Progress: 100%

  t:
    916 812 468 ops/s, ±1.42%   | fastest
916812467.8355056
```

Notice the default cycle output prints `468 ops/s` but `result.ops` is `916812467.8355056`.

I believe the bug lies somewhere in `src/internal/format.ts`.

**Comment by caderek** [comment]
I may be missing something, but it's the intended behavior - the result is rounded according to standard rounding rules, digits are not stripped, just rounded. Does that lead to some problems that I am not aware of?

**Comment by mgartner** [comment]
Oh I see. The whitespace in the number confused me. I read `916 812 468 ops/s` as just `468 ops/s`. Nevermind.
