### ISSUE TITLE
Tooltip isn't shown for small values

### ISSUE THREAD

**Issue by xamgore** [caderek/benny#20]
Thanks for the framework! Imagine we would like to compare two algorithms. Though it's infeasible to see values on the right side — they are slightly above the zero, a tooltip is not shown. I believe from the UI/UX perspective, it could be shown also when the cursor is hovering labels on the X axis. What do you think?

![image](https://user-images.githubusercontent.com/4586392/99954478-e6c45100-2d93-11eb-8ffb-1d8c87986d6c.png)

Seems to be https://github.com/chartjs/Chart.js/issues/4109 related.

**Comment by caderek** [comment]
Fixed in v3.7.0
