### ISSUE TITLE
@types/benchmark should be a runtime dep

### ISSUE THREAD

**Issue by moltar** [caderek/benny#23]
https://github.com/caderek/benny/blob/b4993c45a73f3a2bc6b342b657c775a2d80363e6/package.json#L47

Otherwise when building inside a project, get the following:

```
node_modules/benny/lib/complete.d.ts:1:23 - error TS7016: Could not find a declaration file for module 'benchmark'. '~/foo/node_modules/benchmark/benchmark.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/benchmark` if it exists or add a new declaration (.d.ts) file containing `declare module 'benchmark';`

1 import { Suite } from 'benchmark';
                        ~~~~~~~~~~~
```

**Comment by kirbysayshi** [comment]
I'm not affiliated with this project, but I bet this issue could be solved by setting `skipLibCheck: false` in your tsconfig's compilerSettings. I hope this helps!

**Comment by defunctzombie** [comment]
This issue has been resolved and can be closed.
