### ISSUE TITLE
Async setup returning async test is includes both in clocked function time?

### ISSUE THREAD

**Issue by kirbysayshi** [caderek/benny#27]
Hello! First off, this repo and API looks awesome. Way to go simplifying and covering some of the major pain points of benchmark js!

I was looking through the code, and might have discovered an issue. I could be wrong since the repo is still new to me.

https://github.com/caderek/benny/blob/b4993c45a73f3a2bc6b342b657c775a2d80363e6/src/add.ts#L21

Doesn't this code include the setup execution in the clocked function? Shouldn't it instead be something like:

```diff
  if (returnType === types.Function && getType(test()()) === types.Promise) {
+   const content = test();
    return {
-    rawTest: (deferred: Deferred) => test()().then(() => deferred.resolve()),
+    rawTest: (deferred: Deferred) => content().then(() => deferred.resolve()),
      defer: true,
    }
  }
```

Again, I might just be reading this wrong, and if so, feel free to close.

As I'm looking through the other cases for setup, the common pattern seems to be that the setup is run once, completely outside of benchmark.js (this makes sense since it doesn't support async setup). But there could be a deeper concern here too: only running the setup function once could result in inconsistent start state for the clocked function:

```ts
add('array truncation', async () => {
  const arr = (new Array(1000)).fill(true);
  return async () => {
    // on the first run, this will actually truncate the array.
    // on subsequent runs, the length would already be zero since the setup state is shared.
    arr.length = 0;
  }
})
```

Again, I could be wrong here! Still understanding how things work.

**Comment by caderek** [comment]
The first part was fixed in v3.7.0, thank you!

I will close his one and open a new issue with the second part - as it is not necessarily a bug - setup runs once, but I may consider enhancement to rerun the setup for each benchmark iteration (not sure if it's possible with the current API).

**Comment by kirbysayshi** [comment]
Nice, glad to hear it was fixed :)

**Comment by caderek** [comment]
Sorry that it took me  so long. Thank you!

**Comment by kirbysayshi** [comment]
Oh no worries! It’s open source: things take time and people have lives! Any progress is a treat.
