### ISSUE TITLE
Please provide floating-point precision when reporting ops / second

### ISSUE THREAD

**Issue by emchristiansen** [caderek/benny#30]
I'm benchmarking an expensive computation that takes around 1 second, and Benny just reports "1 ops/s", which isn't informative.
Is it possible to get more precise timing information, and if not, could you please add this as a feature?
Something like 4 points of precision would be ideal.

Thanks!

**Comment by emchristiansen** [comment]
Huh, I just added some more benchmarks and got results like this:

```
  evaluate_token single serial:
    0.88 ops/s, ±1.43%   | fastest

  evaluate_token single threads:
    0.38 ops/s, ±0.99%   | 56.82% slower

  evaluate_token serial:
    0.17 ops/s, ±2.29%   | slowest, 80.68% slower

  evaluate_token parallel:
    0.18 ops/s, ±2.57%   | 79.55% slower
```

But, when I comment out all but the first benchmark I get this:

```
  evaluate_token single serial:
    1 ops/s, ±1.60%   | fastest
```

So I guess I only get that precision when there's more than one benchmark?
It would be nice if Benny _always_ printed with several significant digits.

**Comment by domoritz** [comment]
I think the precision is set so that you can compare the results. If you don't care about comparisons, you can write your own formatter.

For example, here is mine

```js
const formatter = new Intl.NumberFormat();
function formatNumber(number, precision) {
    const rounded = number > precision * 10 ? Math.round(number) : parseFloat((number).toPrecision(precision));
    return formatter.format(rounded)
}

function cycle(result, _summary) {
    const duration = result.details.median * 1000;
    console.log(
        `${kleur.cyan(result.name)} ${formatNumber(result.ops, 3)} ops/s ±${result.margin.toPrecision(2)}%, ${formatNumber(duration, 2)} ms, ${kleur.gray(result.samples + ' samples')}`,
    );
}
```

**Comment by caderek** [comment]
Added in v.3.7.0 via the `configure` function, example:

```javascript
suite(
        'Example 21',

        add('Example', () => {
          // ...some code
        }),

        configure({ minDisplayPrecision: 3 }), // significant digits
        cycle(),
        complete(),
      )
```
