### ISSUE TITLE
Trigger benchmark start / Reset timer

### ISSUE THREAD

**Issue by Shivansh-yadav13** [caderek/benny#48]
I want to write some tests, but I want to start the benchmark after doing some other operations.

e.g.
```js
await suite(
  'BenchmarkRBACModel',
  add('RBAC Model', async () => {
    const e = await getEnforcerWithPath('examples/rbac_model.conf', false);
    for (let i = 0; i < 100; i++) {
      await e.addPolicy(`group${i}`, `data${i / 10}`, 'read');
    }
    
    // start benchmark

    for (let i = 0; i <= 100; i++) {
      await e.enforce('alice', 'data2', 'read');
    }
  }),
  cycle(),
  complete()
);
```

I want to start the benchmark after `// start benchmark`.
or if there is a way to reset timer like in golang testing.

**Comment by StreetStrider** [comment]
@Shivansh-yadav13 you can make a `setup`, that is reflected in [the api docs section](https://github.com/caderek/benny#api). Is it what you wanted to do?
