### ISSUE TITLE
Great module, thanks

### ISSUE THREAD

**Issue by moltar** [caderek/benny#5]
Just wanted to say thanks for the great abstraction over the dated Benchmark module. It feels very fresh and especially appreciated the fact that it is fully typed!

I have swapped out Benchmark for benny here:

https://github.com/moltar/typescript-runtime-type-benchmarks

Thanks!

**Comment by caderek** [comment]
You're welcome,
Cool repo btw! I was recently checking io-ts, definitely have to look into runtypes package.

**Comment by luiscarbonell** [comment]
Ditto this issue title!

Went through pages of NPM to find this repo. It's awesome 💪

**Comment by celesteking** [comment]
This is definitely better than Benchmark.js. Kudos to the dev.
