### ISSUE TITLE
Benchmarking the typescript file itself

### ISSUE THREAD

**Issue by yatesco** [caderek/benny#8]
Hi there - thanks for this!

If I `yarn build` and then `node lib\<package>\benchmark.js` then everything works as expected, however, is there anyway to skip the `yarn build` step so I can run my `benchmark.ts` directly?

(sorry, this might be a newbie Q ;-))

**Comment by caderek** [comment]
Yup,
the simplest solution is to use [ts-node](https://github.com/TypeStrong/ts-node), then you can just run:

```
ts-node benchmark.ts
```

You don't have to even install it, you can use `npx` (comes with node):

```
npx ts-node benchmark.ts
```

**Comment by yatesco** [comment]
Thanks a bunch :-)

**Comment by stephen-smith** [comment]
Didn't work for me:
```
% npx ts-node src/queue.bench.ts
⨯ Unable to compile TypeScript:
src/queue.bench.ts:5:20 - error TS2307: Cannot find module 'benny'.

5 import * as b from "benny";
                     ~~~~~~~
```

All my source is currently typescript, including jest+fast-check tests.  `npm run build` works, but doesn't build the *.bench.ts files because I have webpack only outputting production entry points.
